- name: "Declaring variable at play level"
  hosts: all
  become: true
  connection: local
  vars:
    url: play.example.com
  tasks:
    - name: "Access a variable"
      ansible.builtin.debug:
       msg: url == {{url}}

- name: Declaring variable in task level
  hosts: all
  become: true
  connection: local
  tasks:
    - name: "Declaring variable"
      ansible.builtin.debug:
        msg: url == {{url}}
      vars:
        url: task.example.com

- name: Declaring variable in file level
  hosts: all
  become: true
  connection: local
  vars_files:
    - variable.yml
  tasks:
    - name: "variable in file"
      ansible.builtin.debug:
        msg: url == {{url}}

- name: "Using register"
  hosts: all
  become: true
  connection: local
  tasks:
    - name: using register
      ansible.builtin.shell: date
      register: out
    - name: print out
      ansible.builtin.debug:
        msg: "{{out}}"