- name: "Declaring variable at play level"
  hosts: all
  become: true
  connection: local
  vars:
    url: play.example.com
  tasks:
    - name: "Access a variable"
      ansible.builtin.debug:
       msg: url == {{url}}
