- name: install nginx
  ansible.builtin.service:
    name: nginx

- name: Remove the default content folder
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create HTTP Document Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download code and unzip
  ansible.builtin.unarchive:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy the configuration file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: restart and enable nginx service
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: restarted