- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: including common role
  ansible.builtin.include_role:
    name: common
    tasks_from: app_pre_req


- name: restart and enable nginx service
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: restarted