- name: Disable mysql8 version
  ansible.builtin.shell: dnf module disable mysql -y

- name: Copy the repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL 5.7
  ansible.builtin.yum:
    name: mysql-community-server

- name: Service re-start and enable
  ansible.builtin.systemd:
    state: restarted
    enabled: yes
    name: mysqld

- name: Reset default root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{roboshop_mysql_pass}}

