- name: Install maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: include app re req task
  ansible.builtin.include_tasks: app_pre_req.yml

- name: Maven Build
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: include systemd
  ansible.builtin.include_tasks:
    file: systemd.yml

- name: include schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load