- name: load sql schema
  community.mysql.mysql_db:
    state: import
    name: all
    login_user: root
    login_password: "{{mysql_pass}}"
    login_host: 172.31.1.105
    target: /app/schema/shipping.sql