- name: Setup repos for nodejs
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: including common role
  ansible.builtin.include_role:
    name: common

