- name: Setup repos for nodejs
  ansible.builtin.shell:  curl -s https://rpm.nodesource.com/setup_lts.x | bash


- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: include app re req task
  ansible.builtin.include_tasks:
    file: app_pre_req.yml

- name: install dependencies
  ansible.builtin.npm:
    name: express
    path: /app

- name: include systemd
  ansible.builtin.include_tasks:
    file: systemd.yml

- name: include schema
  ansible.builtin.include_tasks: "{{schema_type}}-"schema.yml
  when: schema_load


