- name: install python compilars
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: include app re req task
  ansible.builtin.include_tasks:
    file: app_pre_req.yml

- name: install dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6

- name: include systemd
  ansible.builtin.include_tasks:
    file: systemd.yml